# Generated by Django 4.1.1 on 2022-09-25 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g_blog_app', '0004_alter_categorypage_name_alter_categorypage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='g_blog_app.categorypage'),
        ),
    ]
