# Generated by Django 4.1.1 on 2022-09-25 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g_blog_app', '0005_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ForeignKey(default='Select a category', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='g_blog_app.categorypage'),
        ),
    ]
